const POSTS = [
  {
    id: 1,
    type: "Competitive",
    game: "Valorant",
    username: "johndoe",
    img: "https://avatar.iran.liara.run/public",
    desctipion: "Need 2 player",
    rank: "Platinum",
  },
  {
    id: 2,
    type: "Casual",
    game: "League of legends",
    username: "janedoe",
    img: "https://avatar.iran.liara.run/public",
    desctipion: "Need 2 player",
    rank: "Platinum",
  },
  {
    id: 3,
    type: "Competitive",
    game: "Dota 2",
    username: "daisyui",
    img: "https://avatar.iran.liara.run/public",
    desctipion: "Need 2 player",
    rank: "Platinum",
  },
  {
    id: 4,
    type: "Tournament",
    game: "Minecraft",
    username: "graydoe",
    img: "https://avatar.iran.liara.run/public",
    desctipion: "Need 2 player",
    rank: "Platinum",
  },
  {
    id: 5,
    type: "Casual",
    game: "Valorant",
    username: "bluedoe",
    img: "https://avatar.iran.liara.run/public",
    desctipion: "Need 2 player",
    rank: "Platinum",
  },
  {
    id: 6,
    type: "Tournament",
    game: "CSGO",
    username: "mikedoe",
    img: "https://avatar.iran.liara.run/public",
    desctipion: "Need 2 player",
    rank: "Platinum",
  },
]

export default POSTS;